version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
# Do not build on tags (GitHub only)
skip_tags: true
platform:
- Win32
  
before_build:
- cmd: premake5.exe vs2017
- ps: >-
    Get-Content .\OpenSndGaelco\src\OpenSndGaelco.rc | ForEach-Object { $_ -replace "1.0.0.0", $env:appveyor_build_version } | Set-Content .\OpenSndGaelco\src\OpenSndGaelco2.rc
    
    del .\OpenSndGaelco\src\OpenSndGaelco.rc
    
    mv .\OpenSndGaelco\src\OpenSndGaelco2.rc .\OpenSndGaelco\src\OpenSndGaelco.rc

build:
  project: OpenSndGaelco.sln
  verbosity: minimal

artifacts:
- path: build\bin\release\output\
  name: OpenSndGaelco
deploy:
- provider: GitHub
  tag: OpenSndGaelco
  release: $(APPVEYOR_BUILD_VERSION)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: a2B+6mDTHuBa0fw8nm739eGJIZBcZp0IenhKvvXvreLR6ZUoHg9pflMP8ahNUK6o
  repository: teknogods/OpenSndGaelco
  artifact: build\bin\release\OpenSndGaelco.zip
  force_update: true
